import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "./common/components/Header";
import { Button, Container } from "reactstrap";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container className="py-5 text-center">
          <h1 className="mt-5 display-1">
            O melhor jeito de comprar o que você ama
          </h1>
          <p className="m-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi iste
            adipisci hic soluta? Rem delectus accusamus veritatis dolorem
            consequatur pariatur facere totam neque quae, corporis suscipit
            velit iusto culpa voluptatibus.
          </p>
          <Link href="/products">
            <Button color="dark" className="px-4 pb-2">
              Conheça nossos produtos!
            </Button>
          </Link>
        </Container>
      </main>
    </>
  );
}
