import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur
          repudiandae culpa minus iusto corrupti commodi enim, voluptatibus iure
          delectus eum quo, impedit nam distinctio natus alias placeat, aliquid
          neque inventore. Alias excepturi sit aperiam voluptate minus numquam
          placeat dicta ducimus incidunt magnam voluptates debitis possimus
          voluptatum porro, non nobis adipisci ex quidem molestiae molestias.
          Dignissimos exercitationem sapiente magni dolores qui.
        </p>
      </main>
    </>
  );
}
